- name: Playbook to Install Maven and Docker
  hosts: webserver
  become: true
  tasks:
  - command: apt-get update
  - name: Install git on worker node
    package: name=git state=present
  - name: install docker on worker node
    package: name=docker.io state=present
  - name: Start docker service
    service: name=docker state=started
